[package]
name = "qute-ctrl"
version = "0.1.1"
authors = ["joylei <leingliu@gmail.com>"]
edition = "2018"

[dependencies]
libc = { version="0.2" }
log = { version="0.4", default-features=false, features=["std"] }
thiserror = "1"
