[package]
name = "qute-ctrl"
version = "0.1.1"
authors = ["joylei <leingliu@gmail.com>"]
edition = "2018"

[dependencies]
libc = { version="*" }
log = { version="*", default-features=false, features=["std"] }
error-chain = { version="*", default-features=false, features=[] }
